project:
  type: website

website:
  title: "<img src='/images/shibainu.png' alt='ISSS608' style='height: 48px; width: 48px;'>"
  back-to-top-navigation: true
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu: 
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3a"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 3b"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_2.html"
    - text: "In-class Exercises"
    - text: "Take-home Exercises"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar: 
    style: "docked"
    background: "#F6F5EB"
    contents:
        - section: "Hands-on Exercises"
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3a"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 3b"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_2.html"
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

