{
  "hash": "4856fbe3da61e2b2fbdf9215b481bcbf",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 3\"\nauthor: \"Yi Fang\"\ndate: \"June 12, 2025\"\ndate-modified: \"last-modified\"\neditor: visual\nfreeze: true\nwarning: false\ncode-fold: TRUE\nformat: html\ncategories: \n  - [\"Take-home Exercise\"]\n---\n\n\n\n# 1 Overview\n\nThis take-home exercise will be done in reference to the [VAST Challenge 2025](https://vast-challenge.github.io/2025/MC1.html) and prepare a Shiny application prototype.\n\n## 1.1 Background\n\nOne of music’s biggest superstars is Oceanus native Sailor Shift. From humble beginnings, Sailor has grown in popularity and now enjoys fans around the world. Sailor started her career on the island nation of Oceanus which can be clearly seen in her early work, she started in the genre of “Oceanus Folk”. While Sailor has moved away from the traditional Oceanus style, the Oceanus Folk has made a name for itself in the musical world. The popularity of this music is one of the factors driving an increase in tourism to a quiet island nation that used to be known for fishing.\n\nIn 2023, Sailor Shift joined the Ivy Echoes – an all-female Oceanus Folk band consisting of Sailor (vocalist), Maya Jensen (vocalist), Lila “Lilly” Hartman (guitarist), Jade Thompson (drummer), and Sophie Ramirez (bassist). They played together at venues throughout Oceanus but had broken up to pursue their individual careers by 2026. Sailor’s breakthrough came in 2028 when one of her singles went viral, launched to the top of the global charts (something no other Oceanus Folk song had ever done). Since then, she has only continued to grow in popularity worldwide.\n\nSailor has released a new album almost every year since her big break, and each has done better than the last. Although she has remained primarily a solo artist, she has also frequently collaborated with other established artists, especially in the Indie Pop and Indie Folk genres. She herself has branched out musically over the years but regularly returns to the Oceanus Folk genre — even as the genre’s influence on the rest of the music world has spread even more.\n\nSailor has always been passionate about two things: (1) spreading Oceanus Folk, and (2) helping lesser-known artists break into music. Because of those goals, she’s particularly famous for her frequent collaborations.\n\nAdditionally, because of Sailor’s success, more attention began to be paid over the years to her previous bandmates. All 4 have continued in the music industry—Maya as an independent vocalist, Lilly and Jade as instrumentalists in other bands, and Sophie as a music producer for a major record label. In various ways, all of them have contributed to the increased influence of Oceanus folk, resulting in a new generation of up-and-coming Oceanus Folk artists seeking to make a name for themselves in the music industry.\n\nNow, as Sailor returns to Oceanus in 2040, a local journalist – Silas Reed – is writing a piece titled Oceanus Folk: Then-and-Now that aims to trace the rise of Sailor and the influence of Oceanus Folk on the rest of the music world. He has collected a large dataset of musical artists, producers, albums, songs, and influences and organized it into a knowledge graph. The task is to help Silas create beautiful and informative visualizations of this data and uncover new and interesting information about Sailor’s past, her rise to stardom, and her influence.\n\n## 1.2 Tasks and Questions\n\nThe objective of this take-home exercise is to complete the following task while addressing VAST Challenge 2025's Mini-Challenge, Question 1.\n\n-   To evaluate and determine the necessary R packages needed for your Shiny application are supported in R CRAN,\n\n-   To prepare and test the specific R codes can be run and returned the correct output as expected,\n\n-   To determine the parameters and outputs that will be exposed on the Shiny applications, and\n\n-   To select the appropriate Shiny UI components for exposing the parameters determine above.\n\nTasks and questions of VAST Challenge 2025's Mini-Challenge 1 are as follows.\n\n1.  Design and develop visualizations and visual analytic tools that will allow Silas to explore and understand the profile of Sailor Shift’s career\n\n    a.  Who has she been most influenced by over time?\n\n    b.  Who has she collaborated with and directly or indirectly influenced?\n\n    c.  How has she influenced collaborators of the broader Oceanus Folk community?\n\n# 2 Getting Started\n\n## 2.1 Load the packages\n\nThe following libraries will be used for this exercise.\n\n**Web Applications**\n\n-   shiny - Build interactive web applications and dashboards with R\n\n**Utility Tools**\n\n-   jsonlite - Parse and generate JSON data\n\n-   tidyverse - Collection of data science packages (dplyr, ggplot2, tidyr, etc.)\n\n-   ggtext - Rich text formatting for ggplot2 labels and annotations\n\n-   knitr - Generate dynamic reports integrating R code and documentation\n\n-   lubridate - Simplify date and time manipulation\n\n-   kableExtra - Create styled and formatted tables\n\n**Graphing Tools**\n\n-   patchwork - Combine multiple ggplot objects into layouts\n\n-   ggraph - Grammar of graphics for network and graph visualization\n\n-   tidygraph - Tidy data manipulation for graphs and networks\n\n-   igraph - Comprehensive network analysis and graph algorithms\n\n-   ggiraph - Add interactivity to ggplot2 graphics\n\n-   plotly - Create interactive, publication-quality visualizations\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(jsonlite, tidyverse, ggtext,\n                knitr, lubridate, patchwork,\n                ggraph, tidygraph, igraph,\n                ggiraph, kableExtra, plotly)\n```\n:::\n\n\n\n## 2.2 Importing Knowledge Graph Data\n\n`fromJSON()` of **jsonlite** package is used to import *MC1_graph.json* file into R and save the output object.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc1_data <- fromJSON(\"MC1/data/MC1_graph.json\")\n```\n:::\n\n\n\n### 2.2.1 Inspect structure\n\nHere, `str()` is used to reveal the structure of *mc1_data* object.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(mc1_data, max.level = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 5\n $ directed  : logi TRUE\n $ multigraph: logi TRUE\n $ graph     :List of 2\n $ nodes     :'data.frame':\t17412 obs. of  10 variables:\n $ links     :'data.frame':\t37857 obs. of  4 variables:\n```\n\n\n:::\n:::\n\n\n\n## 2.3 Extracting the edges and nodes tables\n\nNext, `as_tibble()` of **tibble** package package is used to extract the nodes and links tibble data frames from *mc1_data* object into two separate tibble data frames called *mc1_nodes_raw* and *mc1_edges_raw* respectively.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc1_nodes_raw <- as_tibble(mc1_data$nodes)\nglimpse(mc1_nodes_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 17,412\nColumns: 10\n$ `Node Type`    <chr> \"Song\", \"Person\", \"Person\", \"Person\", \"RecordLabel\", \"S…\n$ name           <chr> \"Breaking These Chains\", \"Carlos Duffy\", \"Min Qin\", \"Xi…\n$ single         <lgl> TRUE, NA, NA, NA, NA, FALSE, NA, NA, NA, NA, TRUE, NA, …\n$ release_date   <chr> \"2017\", NA, NA, NA, NA, \"2026\", NA, NA, NA, NA, \"2020\",…\n$ genre          <chr> \"Oceanus Folk\", NA, NA, NA, NA, \"Lo-Fi Electronica\", NA…\n$ notable        <lgl> TRUE, NA, NA, NA, NA, TRUE, NA, NA, NA, NA, TRUE, NA, N…\n$ id             <int> 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 1…\n$ written_date   <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, \"2020\", NA, NA,…\n$ stage_name     <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ notoriety_date <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n```\n\n\n:::\n\n```{.r .cell-code}\nkable(head(mc1_nodes_raw, 5))\n```\n\n::: {.cell-output-display}\n\n\n|Node Type   |name                  |single |release_date |genre        |notable | id|written_date |stage_name |notoriety_date |\n|:-----------|:---------------------|:------|:------------|:------------|:-------|--:|:------------|:----------|:--------------|\n|Song        |Breaking These Chains |TRUE   |2017         |Oceanus Folk |TRUE    |  0|NA           |NA         |NA             |\n|Person      |Carlos Duffy          |NA     |NA           |NA           |NA      |  1|NA           |NA         |NA             |\n|Person      |Min Qin               |NA     |NA           |NA           |NA      |  2|NA           |NA         |NA             |\n|Person      |Xiuying Xie           |NA     |NA           |NA           |NA      |  3|NA           |NA         |NA             |\n|RecordLabel |Nautical Mile Records |NA     |NA           |NA           |NA      |  4|NA           |NA         |NA             |\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmc1_edges_raw <- as_tibble(mc1_data$links)\n\nglimpse(mc1_edges_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 37,857\nColumns: 4\n$ `Edge Type` <chr> \"InterpolatesFrom\", \"RecordedBy\", \"PerformerOf\", \"Composer…\n$ source      <int> 0, 0, 1, 1, 2, 2, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5…\n$ target      <int> 1841, 4, 0, 16180, 0, 16180, 0, 5088, 14332, 11677, 2479, …\n$ key         <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n```\n\n\n:::\n\n```{.r .cell-code}\nkable(head(mc1_edges_raw))\n```\n\n::: {.cell-output-display}\n\n\n|Edge Type        | source| target| key|\n|:----------------|------:|------:|---:|\n|InterpolatesFrom |      0|   1841|   0|\n|RecordedBy       |      0|      4|   0|\n|PerformerOf      |      1|      0|   0|\n|ComposerOf       |      1|  16180|   0|\n|PerformerOf      |      2|      0|   0|\n|ProducerOf       |      2|  16180|   0|\n\n\n:::\n:::\n\n\n\n## 2.4 Data Overview\n\nBefore proceeding to data pre-processing, we examine the data to gain a clearer understanding of the dataset and to verify the structural integrity of the imported graph.\n\nIn this code chunk below, ggplot2 functions are used the reveal the frequency distribution of *Node Type* field of *mc1_nodes_raw*.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mc1_nodes_raw,\n       aes(y = `Node Type`)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\nOn the other hand, code chunk below uses ggplot2 functions to reveal the frequency distribution of *Edge Type* field of *mc1_edges_raw*.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mc1_edges_raw,\n       aes(y = `Edge Type`)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n# 3 Data Preparation\n\nThere are 2 columns that provides information on names, the *name* and *stage_name* column. The code below shows that the *name* column is the one that contains information on the target of interest, Sailor Shift, for this module.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(mc1_nodes_raw %>%\n  filter(grepl(\"Sailor Shift\", name))) #Sailor Shift is in name column and not in stage_name column\n```\n\n::: {.cell-output-display}\n\n\n|Node Type |name         |single |release_date |genre |notable |    id|written_date |stage_name |notoriety_date |\n|:---------|:------------|:------|:------------|:-----|:-------|-----:|:------------|:----------|:--------------|\n|Person    |Sailor Shift |NA     |NA           |NA    |NA      | 17255|NA           |NA         |NA             |\n\n\n:::\n:::\n\n\n\n## 3.1 Adding identifying columns\n\nAs a large part of this mini-challenge centers around Sailor Shift and the genre of \"Oceanus Folk\", the following code will add columns to help with identification and filtering of Sailor Shift and the work in the genre of \"Oceanus Folk\". This will help with analysis in addressing the questions and tasks.\n\nHere's an illustration of the columns.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc1_nodes_raw <- mc1_nodes_raw %>%\n  mutate(\n    is_sailor = (\n      str_detect(name, regex(\"sailor shift\", ignore_case = TRUE))\n    ) %>% replace_na(FALSE),\n    \n    is_oceanus_folk = str_detect(genre, regex(\"oceanus folk\", ignore_case = TRUE)) %>% #na/not oceanus folk = false\n      replace_na(FALSE)\n  )\n\nkable(head(mc1_nodes_raw,5))\n```\n\n::: {.cell-output-display}\n\n\n|Node Type   |name                  |single |release_date |genre        |notable | id|written_date |stage_name |notoriety_date |is_sailor |is_oceanus_folk |\n|:-----------|:---------------------|:------|:------------|:------------|:-------|--:|:------------|:----------|:--------------|:---------|:---------------|\n|Song        |Breaking These Chains |TRUE   |2017         |Oceanus Folk |TRUE    |  0|NA           |NA         |NA             |FALSE     |TRUE            |\n|Person      |Carlos Duffy          |NA     |NA           |NA           |NA      |  1|NA           |NA         |NA             |FALSE     |FALSE           |\n|Person      |Min Qin               |NA     |NA           |NA           |NA      |  2|NA           |NA         |NA             |FALSE     |FALSE           |\n|Person      |Xiuying Xie           |NA     |NA           |NA           |NA      |  3|NA           |NA         |NA             |FALSE     |FALSE           |\n|RecordLabel |Nautical Mile Records |NA     |NA           |NA           |NA      |  4|NA           |NA         |NA             |FALSE     |FALSE           |\n\n\n:::\n:::\n\n\n\n## 3.2 Converting date field\n\nDate fields will be converted from *chr* to *int* for later analysis. Note that dates only appear for *Song* and *Album*.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc1_nodes_raw <- mc1_nodes_raw %>%\n  mutate(across(c(release_date, notoriety_date, written_date),\n                ~as.integer(if_else(`Node Type` %in% c(\"Song\", \"Album\"), ., NA_character_))))\n```\n:::\n\n\n\n## 3.3 Check for duplicates\n\n### 3.3.1 Check for duplicates in *mc1_nodes_raw*\n\nThe following code chunk checks for *id* duplicates in *mc1_nodes_raw.*\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc1_nodes_raw %>%\n  count(id) %>%\n  filter(n > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 2\n# ℹ 2 variables: id <int>, n <int>\n```\n\n\n:::\n:::\n\n\n\nThere are no duplicated *id* in *mc1_nodes_raw*.\n\nThe following code checks for *name* duplicates in *mc1_nodes_raw*.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nduplicated_name <- mc1_nodes_raw %>%\n  count(name) %>%\n  filter(n > 1)\n\nduplicated_name\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,611 × 2\n   name                 n\n   <chr>            <int>\n 1 Agata Records        2\n 2 Ancestral Echoes     2\n 3 Angela Thompson      2\n 4 Anthony Davis        2\n 5 Anthony Smith        2\n 6 Asuka Takahashi      3\n 7 Brandon Wilson       2\n 8 Brian Gonzalez       2\n 9 Bryan Garcia         2\n10 Bryan Smith          3\n# ℹ 1,601 more rows\n```\n\n\n:::\n:::\n\n\n\nThe following code chunk shows rows from *mc1_nodes_raw* that have duplicated names, and sorting them alphabetically by the *name* column. There are a total of 4,953 records with duplicated names in *mc1_nodes_raw*.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc1_nodes_raw %>%\n  filter(name %in% duplicated_name$name) %>%\n  arrange(name)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4,953 × 12\n   `Node Type` name         single release_date genre notable    id written_date\n   <chr>       <chr>        <lgl>         <int> <chr> <lgl>   <int>        <int>\n 1 RecordLabel Agata Recor… NA               NA <NA>  NA       1528           NA\n 2 RecordLabel Agata Recor… NA               NA <NA>  NA      17388           NA\n 3 Song        Ancestral E… TRUE           1991 Drea… FALSE   11793           NA\n 4 Song        Ancestral E… FALSE          2039 Avan… TRUE    17133           NA\n 5 Person      Angela Thom… NA               NA <NA>  NA       1150           NA\n 6 Person      Angela Thom… NA               NA <NA>  NA      13448           NA\n 7 Person      Anthony Dav… NA               NA <NA>  NA       8692           NA\n 8 Person      Anthony Dav… NA               NA <NA>  NA      12452           NA\n 9 Person      Anthony Smi… NA               NA <NA>  NA       5719           NA\n10 Person      Anthony Smi… NA               NA <NA>  NA       7694           NA\n# ℹ 4,943 more rows\n# ℹ 4 more variables: stage_name <chr>, notoriety_date <int>, is_sailor <lgl>,\n#   is_oceanus_folk <lgl>\n```\n\n\n:::\n:::\n\n\n\n### 3.3.2 Fixing duplicates in *mc1_nodes_raw*\n\nThe section will focus on fixing the duplicates found in *mc1_nodes_raw* as identified in section 3.3.1*.*\n\nThe following code chunk will tag each row with a unique key (*group_key*) based on its respective column values. This helps to identify unique records.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Mark all node rows with a hash key for grouping\nmc1_nodes_tagged <- mc1_nodes_raw %>%\n  mutate(group_key = paste(`Node Type`, name, single, release_date, genre,\n                           notable, written_date, notoriety_date, is_sailor,\n                           is_oceanus_folk, sep = \"|\"))\n\nkable(head(mc1_nodes_tagged,5))\n```\n\n::: {.cell-output-display}\n\n\n|Node Type   |name                  |single | release_date|genre        |notable | id| written_date|stage_name | notoriety_date|is_sailor |is_oceanus_folk |group_key                                                                                                            |\n|:-----------|:---------------------|:------|------------:|:------------|:-------|--:|------------:|:----------|--------------:|:---------|:---------------|:--------------------------------------------------------------------------------------------------------------------|\n|Song        |Breaking These Chains |TRUE   |         2017|Oceanus Folk |TRUE    |  0|           NA|NA         |             NA|FALSE     |TRUE            |Song&#124;Breaking These Chains&#124;TRUE&#124;2017&#124;Oceanus Folk&#124;TRUE&#124;NA&#124;NA&#124;FALSE&#124;TRUE |\n|Person      |Carlos Duffy          |NA     |           NA|NA           |NA      |  1|           NA|NA         |             NA|FALSE     |FALSE           |Person&#124;Carlos Duffy&#124;NA&#124;NA&#124;NA&#124;NA&#124;NA&#124;NA&#124;FALSE&#124;FALSE                       |\n|Person      |Min Qin               |NA     |           NA|NA           |NA      |  2|           NA|NA         |             NA|FALSE     |FALSE           |Person&#124;Min Qin&#124;NA&#124;NA&#124;NA&#124;NA&#124;NA&#124;NA&#124;FALSE&#124;FALSE                            |\n|Person      |Xiuying Xie           |NA     |           NA|NA           |NA      |  3|           NA|NA         |             NA|FALSE     |FALSE           |Person&#124;Xiuying Xie&#124;NA&#124;NA&#124;NA&#124;NA&#124;NA&#124;NA&#124;FALSE&#124;FALSE                        |\n|RecordLabel |Nautical Mile Records |NA     |           NA|NA           |NA      |  4|           NA|NA         |             NA|FALSE     |FALSE           |RecordLabel&#124;Nautical Mile Records&#124;NA&#124;NA&#124;NA&#124;NA&#124;NA&#124;NA&#124;FALSE&#124;FALSE         |\n\n\n:::\n:::\n\n\n\nThe code below deduplicates the dataset using *group_key*, reducing the number of duplicated names from 4,953 to 14. The remaining 14 names appear more than once because their corresponding records differ in at least one column used to form *group_key*, so they are retained as distinct entries.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 2: Deduplicate and keep the preferred (with stage_name if available)\nmc1_nodes_dedup <- mc1_nodes_tagged %>%\n  group_by(group_key) %>%\n  arrange(desc(!is.na(stage_name))) %>%\n  slice(1) %>%\n  ungroup()\n\nduplicated_name <- mc1_nodes_dedup %>%\n  count(name) %>%\n  filter(n > 1)\n\nmc1_nodes_raw %>%\n  filter(name %in% duplicated_name$name) %>%\n  arrange(name) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Node Type   |name                   |single | release_date|genre            |notable |    id| written_date|stage_name | notoriety_date|is_sailor |is_oceanus_folk |\n|:-----------|:----------------------|:------|------------:|:----------------|:-------|-----:|------------:|:----------|--------------:|:---------|:---------------|\n|Song        |Ancestral Echoes       |TRUE   |         1991|Dream Pop        |FALSE   | 11793|           NA|NA         |             NA|FALSE     |FALSE           |\n|Song        |Ancestral Echoes       |FALSE  |         2039|Avant-Garde Folk |TRUE    | 17133|           NA|NA         |             NA|FALSE     |FALSE           |\n|RecordLabel |Coastal Echoes         |NA     |           NA|NA               |NA      |  4022|           NA|NA         |             NA|FALSE     |FALSE           |\n|Album       |Coastal Echoes         |NA     |         2023|Psychedelic Rock |TRUE    | 15065|         2019|NA         |           2039|FALSE     |FALSE           |\n|Song        |Postcards from Nowhere |TRUE   |         2023|Indie Folk       |TRUE    | 12852|         2023|NA         |             NA|FALSE     |FALSE           |\n|Song        |Postcards from Nowhere |FALSE  |         1984|Acoustic Folk    |FALSE   | 17214|           NA|NA         |             NA|FALSE     |FALSE           |\n|Album       |Shattered Reflections  |NA     |         2013|Emo/Pop Punk     |TRUE    |  3325|         2013|NA         |           2013|FALSE     |FALSE           |\n|Song        |Shattered Reflections  |FALSE  |         2036|Darkwave         |TRUE    | 17088|           NA|NA         |             NA|FALSE     |FALSE           |\n|Song        |Unheard Frequencies    |TRUE   |         2025|Alternative Rock |TRUE    |  7999|           NA|NA         |             NA|FALSE     |FALSE           |\n|RecordLabel |Unheard Frequencies    |NA     |           NA|NA               |NA      | 10952|           NA|NA         |             NA|FALSE     |FALSE           |\n|Song        |Vanishing Point        |TRUE   |         2018|Avant-Garde Folk |TRUE    |  9371|         2018|NA         |             NA|FALSE     |FALSE           |\n|Song        |Vanishing Point        |FALSE  |         2013|Oceanus Folk     |FALSE   | 17338|           NA|NA         |             NA|FALSE     |TRUE            |\n|RecordLabel |Vertical Horizon       |NA     |           NA|NA               |NA      |  2453|           NA|NA         |             NA|FALSE     |FALSE           |\n|Album       |Vertical Horizon       |NA     |         2017|Doom Metal       |TRUE    |  9262|           NA|NA         |             NA|FALSE     |FALSE           |\n\n\n:::\n:::\n\n\n\n### 3.3.3 Check for duplicates in *mc1_edges_raw*\n\nThe following code proceeds to check for duplicates in *mc1_edges_raw.*\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Identify duplicate combinations\nduplicate_summary <- mc1_edges_raw %>%\n  count(source, target, `Edge Type`) %>%\n  filter(n > 1)\n\n# Step 2: Join back to get all original duplicate rows\nmc1_edges_raw %>%\n  inner_join(duplicate_summary, by = c(\"source\", \"target\", \"Edge Type\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  `Edge Type` source target   key     n\n  <chr>        <int>  <int> <int> <int>\n1 PerformerOf  17057  17058     0     2\n2 PerformerOf  17057  17058     1     2\n3 PerformerOf  17349  17350     0     2\n4 PerformerOf  17349  17350     2     2\n5 PerformerOf  17355  17356     0     2\n6 PerformerOf  17355  17356     2     2\n```\n\n\n:::\n:::\n\n\n\nThere are duplicates as seen above, with only differences in *key*. As *key* will not be used in subsequent data analysis, the duplicated edges will be removed with the following code.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc1_edges_raw <- mc1_edges_raw %>%\n  distinct(source, target, `Edge Type`, .keep_all = TRUE) %>%\n  select(!key)\n\nmc1_edges_raw %>%\n  count(source, target, `Edge Type`) %>%\n  filter(n > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 4\n# ℹ 4 variables: source <int>, target <int>, Edge Type <chr>, n <int>\n```\n\n\n:::\n:::\n\n\n\n## 3.4 Mapping Node *name* to Edges *id*\n\ntidygraph uses *from* and *to* columns to reference nodes. By default, tidygraph matches these edges reference against the first column in the nodes table, or against *name* column.\n\nCurrently, *source* and *target* columns in *mc1_edges_raw* contain *id* values that correspond to the *id* column in *mc1_nodes_clean*. To properly integrate with tidygraph's conventions, the following will be done:\n\n1.  Restructure *mc1_nodes_clean*\n    a.  Rename the current *name* column to *node_name* - this is done to preserve the actual node names\n    b.  Rename the *id* column to *name* so it becomes the primary identifier column that tidygraph will use for matching\n2.  Rename *source* and *target* columns in *mc1_edges_raw*, as required by tidygraph\n3.  Ensure data type consistency: Convert the *name* column (formerly *id*) to character format to match the data type of the edge references\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc1_nodes_clean <- mc1_nodes_dedup %>%\n  rename(node_name = name, name = id) %>%\n  mutate(name = as.character(name)) %>%\n  select(`Node Type`, node_name, release_date, genre, notable, name, single, written_date, stage_name, notoriety_date, is_sailor, is_oceanus_folk)\n\nkable(head(mc1_nodes_clean,5))\n```\n\n::: {.cell-output-display}\n\n\n|Node Type |node_name                  | release_date|genre                 |notable |name  |single | written_date|stage_name | notoriety_date|is_sailor |is_oceanus_folk |\n|:---------|:--------------------------|------------:|:---------------------|:-------|:-----|:------|------------:|:----------|--------------:|:---------|:---------------|\n|Album     |A Lush Dystopia            |         2031|Psychedelic Rock      |TRUE    |17005 |NA     |         2030|NA         |             NA|FALSE     |FALSE           |\n|Album     |Addicted to Your Heartache |         2004|Southern Gothic Rock  |TRUE    |14658 |NA     |         2000|NA         |             NA|FALSE     |FALSE           |\n|Album     |Adriatic Empress           |         2013|Post-Apocalyptic Folk |TRUE    |10412 |NA     |           NA|NA         |             NA|FALSE     |FALSE           |\n|Album     |Aerial Echoes of Freedom   |         2023|Indie Rock            |TRUE    |7908  |NA     |           NA|NA         |             NA|FALSE     |FALSE           |\n|Album     |Aftershock Silence         |         2028|Dream Pop             |TRUE    |2030  |NA     |         2021|NA         |             NA|FALSE     |FALSE           |\n\n\n:::\n:::\n\n\n\n### 3.4.1 Creating edge mapping from old id to kept id\n\nIn section 3.3.2, duplicated nodes were deduplicated and removed, edges referring to the removed nodes will become invalid thus, edges will be remapped to the retained nodes. This step ensures that all edges correctly point to existing nodes in the deduplicated graph.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Create mapping of all group_key → kept id\nkey_to_id_map <- mc1_nodes_dedup %>%\n  select(group_key, kept_id = id)\n\n# Step 2: Map all original rows to the retained ID\nid_remap <- mc1_nodes_tagged %>%\n  left_join(key_to_id_map, by = \"group_key\") %>%\n  select(original_id = id, kept_id)\n\nid_remap\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 17,412 × 2\n   original_id kept_id\n         <int>   <int>\n 1           0       0\n 2           1       1\n 3           2   14470\n 4           3       3\n 5           4       4\n 6           5       5\n 7           6       6\n 8           7       7\n 9           8       8\n10           9       9\n# ℹ 17,402 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 3: Replace edges' source and target with mapped kept_id\nmc1_edges_mapped <- mc1_edges_raw %>%\n  left_join(id_remap, by = c(\"source\" = \"original_id\"))\n\nmc1_edges_mapped\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 37,854 × 4\n   `Edge Type`      source target kept_id\n   <chr>             <int>  <int>   <int>\n 1 InterpolatesFrom      0   1841       0\n 2 RecordedBy            0      4       0\n 3 PerformerOf           1      0       1\n 4 ComposerOf            1  16180       1\n 5 PerformerOf           2      0   14470\n 6 ProducerOf            2  16180   14470\n 7 PerformerOf           3      0       3\n 8 InterpolatesFrom      5   5088       5\n 9 InStyleOf             5  14332       5\n10 InterpolatesFrom      5  11677       5\n# ℹ 37,844 more rows\n```\n\n\n:::\n:::\n\n\n\nThis step renames *source* and *target* columns to *from* and *to* respectively as required by tidygraph.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc1_edges_mapped <- mc1_edges_mapped %>%\n  mutate(source = kept_id) %>%\n  select(-kept_id) %>%\n  left_join(id_remap, by = c(\"target\" = \"original_id\")) %>%\n  mutate(target = kept_id) %>%\n  select(-kept_id) %>%\n  rename(from = source, to = target) %>%\n  mutate(from = as.character(from), to = as.character(to))\n\nmc1_edges_mapped\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 37,854 × 3\n   `Edge Type`      from  to   \n   <chr>            <chr> <chr>\n 1 InterpolatesFrom 0     1841 \n 2 RecordedBy       0     4    \n 3 PerformerOf      1     0    \n 4 ComposerOf       1     16180\n 5 PerformerOf      14470 0    \n 6 ProducerOf       14470 16180\n 7 PerformerOf      3     0    \n 8 InterpolatesFrom 5     5088 \n 9 InStyleOf        5     14332\n10 InterpolatesFrom 5     11677\n# ℹ 37,844 more rows\n```\n\n\n:::\n:::\n\n\n\n## 3.5 Remove unmatched edges\n\nThe following code chunk removes edges that reference missing node id, ensuring that only valid edges are kept.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc1_edges_clean <- mc1_edges_mapped %>%\n  filter(!is.na(from), !is.na(to))\n```\n:::\n\n\n\nThere are no unmatched edges.\n\n## 3.6 Check for missing nodes\n\nThe following code chunk checks for missing nodes being referenced in *mc1_edges_clean* that do not exist in *mc1_nodes_clean*.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsetdiff(\n  unique(c(mc1_edges_clean$from, mc1_edges_clean$to)),\n  mc1_nodes_clean$name\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncharacter(0)\n```\n\n\n:::\n:::\n\n\n\nThere are no missing nodes.\n\n## 3.7 Validate Edges Schema\n\nThis section aims to ensure that each edge in the graph adheres to the schema specified in the VAST Challenge 2025 MC1 Data Description document. The following code checks whether the node types connect by each edge matches the valid source and target types for that edge's type.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define valid source and destination types for each edge type\nedge_rules <- list(\n  PerformerOf = list(source = c(\"Person\", \"MusicalGroup\"), target = c(\"Song\", \"Album\")),\n  ComposerOf = list(source = c(\"Person\"), target = c(\"Song\", \"Album\")),\n  ProducerOf = list(source = c(\"Person\", \"RecordLabel\"), target = c(\"Song\", \"Album\", \"Person\", \"MusicalGroup\")),\n  LyricistOf = list(source = c(\"Person\"), target = c(\"Song\", \"Album\")),\n  RecordedBy = list(source = c(\"Song\", \"Album\"), target = c(\"RecordLabel\")),\n  DistributedBy = list(source = c(\"Song\", \"Album\"), target = c(\"RecordLabel\")),\n  InStyleOf = list(source = c(\"Song\", \"Album\"), target = c(\"Song\", \"Album\", \"Person\", \"MusicalGroup\")),\n  InterpolatesFrom = list(source = c(\"Song\", \"Album\"), target = c(\"Song\", \"Album\")),\n  CoverOf = list(source = c(\"Song\", \"Album\"), target = c(\"Song\", \"Album\")),\n  LyricalReferenceTo = list(source = c(\"Song\", \"Album\"), target = c(\"Song\", \"Album\")),\n  DirectlySamples = list(source = c(\"Song\", \"Album\"), target = c(\"Song\", \"Album\")),\n  MemberOf = list(source = c(\"Person\"), target = c(\"MusicalGroup\"))\n)\n```\n:::\n\n\n\nThe following code chunk checks for any erroneous edge and node relationships defined in the code chunk above.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a lookup for node types\nnode_type_lookup <- mc1_nodes_clean %>%\n  select(name, `Node Type`) %>%\n  deframe()\n\n# Add source and target node types to the edge table\nmc1_edges_checked <- mc1_edges_clean %>%\n  mutate(\n    source_type = node_type_lookup[from],\n    target_type = node_type_lookup[to]\n  )\n\nmc1_edges_tagged <- mc1_edges_checked %>%\n  rowwise() %>%\n  mutate(\n    valid = {\n      rule <- edge_rules[[`Edge Type`]]\n      if (is.null(rule)) TRUE\n      else {\n        source_type %in% rule$source && target_type %in% rule$target\n      }\n    }\n  ) %>%\n  ungroup()\n\n# Count and display invalid edge combinations\ninvalid_edge_summary <- mc1_edges_tagged %>%\n  filter(!valid) %>%\n  count(`Edge Type`, source_type, target_type, sort = TRUE)\n\nprint(invalid_edge_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 24 × 4\n   `Edge Type`      source_type  target_type      n\n   <chr>            <chr>        <chr>        <int>\n 1 LyricistOf       MusicalGroup Song           106\n 2 RecordedBy       RecordLabel  Album          102\n 3 ProducerOf       MusicalGroup Song           100\n 4 ComposerOf       MusicalGroup Song            97\n 5 ProducerOf       MusicalGroup Album           31\n 6 LyricistOf       MusicalGroup Album           28\n 7 ComposerOf       MusicalGroup Album           17\n 8 InStyleOf        MusicalGroup MusicalGroup    12\n 9 InStyleOf        Person       MusicalGroup    11\n10 InterpolatesFrom MusicalGroup MusicalGroup    10\n# ℹ 14 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check total invalid edge count\ncat(\"Total invalid edges:\", sum(!mc1_edges_tagged$valid), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal invalid edges: 550 \n```\n\n\n:::\n:::\n\n\n\nThere are 550 edges that do not adhere to the schema specified in the data description file provided. The following code will remove these edges.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Keep only valid edges\nmc1_edges_clean <- mc1_edges_tagged %>%\n  filter(valid) %>%\n  select(from, to, `Edge Type`)  # drop helper columns\n```\n:::\n\n\n\n## 3.8 Temporal Validation\n\nTo ensure the integrity of influence relationships between songs and albums, the following code checks for temporal consistency. It verifies that an influenced song or album is not released before the song or album that purportedly influenced it. Any such inconsistencies are flagged as temporal violations.\n\nThere are a total of 84 violations, these edges will be considered invalid and removed in the next section.\n\nBelow is a breakdown of the edge type. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define which edge types represent influence relationships between songs/albums\ninfluence_edge_types <- c(\"InStyleOf\", \"InterpolatesFrom\", \"CoverOf\", \n                         \"LyricalReferenceTo\", \"DirectlySamples\")\n\n# Check for temporal inconsistencies in song/album influence relationships\ntemporal_check <- mc1_edges_clean %>%\n  # Focus only on influence edge types\n  filter(`Edge Type` %in% influence_edge_types) %>%\n  # Add source node info (the influenced song/album)\n  left_join(mc1_nodes_clean %>% \n            select(name, source_type = `Node Type`, source_release = release_date), \n            by = c(\"from\" = \"name\")) %>%\n  # Add target node info (the influencer song/album)\n  left_join(mc1_nodes_clean %>% \n            select(name, target_type = `Node Type`, target_release = release_date), \n            by = c(\"to\" = \"name\")) %>%\n  # Only check Song/Album -> Song/Album relationships\n  filter(source_type %in% c(\"Song\", \"Album\"),\n         target_type %in% c(\"Song\", \"Album\")) %>%\n  # Check for temporal violations\n  mutate(\n    temporal_violation = case_when(\n      is.na(source_release) | is.na(target_release) ~ FALSE,  # Skip if dates missing\n      source_release < target_release ~ TRUE,  # Influenced before influencer\n      TRUE ~ FALSE\n    )\n  )\n\n# Summary of temporal violations\nviolation_summary <- temporal_check %>%\n  filter(temporal_violation) %>%\n  count(`Edge Type`, sort = TRUE)\n\nkable(head(violation_summary))\n```\n\n::: {.cell-output-display}\n\n\n|Edge Type          |  n|\n|:------------------|--:|\n|InStyleOf          | 28|\n|LyricalReferenceTo | 19|\n|CoverOf            | 17|\n|InterpolatesFrom   | 15|\n|DirectlySamples    |  5|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntotal_violations <- sum(temporal_check$temporal_violation, na.rm = TRUE)\ntotal_checked <- nrow(temporal_check)\ncat(\"Total song/album influence relationships checked:\", total_checked)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal song/album influence relationships checked: 7340\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Total temporal violations found:\", total_violations)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal temporal violations found: 84\n```\n\n\n:::\n:::\n\n\n\nHere are some examples of the violations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Show examples of violations with node names\nviolation_examples <- temporal_check %>%\n  filter(temporal_violation) %>%\n  left_join(mc1_nodes_clean %>% select(name, source_name = node_name), \n            by = c(\"from\" = \"name\")) %>%\n  left_join(mc1_nodes_clean %>% select(name, target_name = node_name), \n            by = c(\"to\" = \"name\")) %>%\n  select(source_name, target_name, `Edge Type`, source_release, target_release) %>%\n  arrange(source_release)\n  \n\nkable(head(violation_examples,5))\n```\n\n::: {.cell-output-display}\n\n\n|source_name                   |target_name                  |Edge Type        | source_release| target_release|\n|:-----------------------------|:----------------------------|:----------------|--------------:|--------------:|\n|Sacred Invocation             |The Calm Chorus              |CoverOf          |           1987|           1989|\n|Lucifer's Rhythm              |Whispers of Self-Destruction |CoverOf          |           1994|           1996|\n|The Ballad of Billy's Bravado |Resilience of the Spirit     |InterpolatesFrom |           1997|           2000|\n|Salt and Silence              |Mercy's Melody               |InStyleOf        |           1997|           1999|\n|Culloden's Lament             |Shattered Pieces             |InterpolatesFrom |           1998|           2000|\n\n\n:::\n:::\n\n\n\n\n#### 3.8.1 Removing edges that have temporal issues\n\nThe following code chunk will remove all edges which was highlighted in Section 3.8 that has violated the temporal influence.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get all edges that are not influence relationships (keep as-is)\nnon_influence_edges <- mc1_edges_clean %>%\n  filter(!(`Edge Type` %in% influence_edge_types))\n\n# Get temporally consistent influence edges\nconsistent_influence_edges <- temporal_check %>%\n  filter(!temporal_violation) %>%\n  select(from, to, `Edge Type`)\n\n# Combine all valid edges\nmc1_edges_clean <- bind_rows(non_influence_edges, consistent_influence_edges)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntotal_cleaned_influences <- consistent_influence_edges %>% nrow()\ncat(\"Total song/album influence relationships after cleaning:\", total_cleaned_influences)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal song/album influence relationships after cleaning: 7256\n```\n\n\n:::\n:::\n\n\n\n## 3.9 Check for orphan nodes\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get all node IDs that appear in edges (either as source or target)\nnodes_with_edges <- unique(c(mc1_edges_clean$from, mc1_edges_clean$to))\n\n# Find nodes that don't appear in any edges\norphan_nodes <- mc1_nodes_clean %>%\n  filter(!name %in% nodes_with_edges)\n\n# Summary of orphan nodes\ncat(\"Total nodes:\", nrow(mc1_nodes_clean))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal nodes: 14077\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Nodes with edges:\", length(nodes_with_edges))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNodes with edges: 14077\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Orphan nodes (no edges):\", nrow(orphan_nodes))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOrphan nodes (no edges): 0\n```\n\n\n:::\n:::\n\n\n\n## 3.10 Creating consistent visualisation colouring\n\nThe code below groups different types of edges and nodes into broader categories for consistent visualisation colouring.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\nmc1_edges_clean <- mc1_edges_clean %>%\n  mutate(`Edge Colour` = case_when(\n    `Edge Type` %in% c(\"PerformerOf\", \"ComposerOf\", \"ProducerOf\", \"LyricistOf\", \"RecordedBy\", \"DistributedBy\") ~ \"Creator Of\",\n    `Edge Type` %in% c(\"InStyleOf\", \"InterpolatesFrom\", \"CoverOf\", \"LyricalReferenceTo\", \"DirectlySamples\") ~ \"Influenced By\",\n    `Edge Type` == \"MemberOf\" ~ \"Member Of\",\n    TRUE ~ \"Other\"\n  ))\n\nmc1_nodes_clean <- mc1_nodes_clean %>%\n  mutate(\n    `Node Colour` = case_when(\n      `Node Type` %in% c(\"Person\", \"MusicalGroup\", \"RecordLabel\") ~ \"Musician\",\n      genre == \"Oceanus Folk\" ~ \"Oceanus Folk\",\n      TRUE ~ \"Other Genre\"\n    )\n  )\n```\n:::\n\n\n\n# 4 EDA\n\n## 4.1 Visualising Edge and Node types\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mc1_edges_clean,\n       aes(y = `Edge Type`)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mc1_nodes_clean,\n       aes(y = `Node Type`)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n\n## 4.2 Creating knowledge graph\n\ntbl_graph() is used to create tidygraph's graph object by using the following code chunk.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmusic = tbl_graph(edges = mc1_edges_clean,\n                             nodes = mc1_nodes_clean,\n                             directed = TRUE)\n\nclass(music)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"tbl_graph\" \"igraph\"   \n```\n\n\n:::\n:::\n\n\n\nSeveral of the ggraph layouts involve randomisation. In order to ensure reproducibility, it is necessary to set the seed value before plotting by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n```\n:::\n",
    "supporting": [
      "Take-home_Ex03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}